import { Seeder } from '@jorgebodega/typeorm-seeding';
import { DataSource } from 'typeorm';
import { User } from '../../entities/user.entity';
import * as bcrypt from 'bcrypt';

export default class UserSeeder extends Seeder {
  async run(dataSource: DataSource): Promise<any> {
    await dataSource
      .createQueryBuilder()
      .insert()
      .into(User)
      .values([
        {
          name: 'Lê Đức Sơn',
          gender: '1',
          avatar: 'https://i.pravatar.cc/300',
          email: 'user1@gmail.com',
          phone: '0123456789',
          level: '3',
          certificate: 'https://i.pravatar.cc/300',
          province: '2',
          password: await bcrypt.hash('password', 10),
          birthday: '1999-01-01',
          nationality: 'VN',
        },
        {
          name: 'Lương Thị Tâm',
          gender: '2',
          avatar: 'https://i.pravatar.cc/300',
          email: 'user2@gmail.com',
          phone: '0123456789',
          level: '2',
          certificate: 'https://i.pravatar.cc/300',
          province: '1',
          password: await bcrypt.hash('password', 10),
          birthday: '1999-01-01',
          nationality: 'VN',
        },
        {
          name: 'Lê Minh Đức',
          gender: '1',
          avatar: 'https://i.pravatar.cc/300',
          email: 'user3@gmail.com',
          phone: '0123456789',
          level: '5',
          certificate: 'https://i.pravatar.cc/300',
          province: '5',
          password: await bcrypt.hash('password', 10),
          birthday: '1999-01-01',
          nationality: 'VN',
        },
        {
          name: 'Đinh Thị Thu Hà',
          gender: '2',
          avatar: 'https://i.pravatar.cc/300',
          email: 'user4@gmail.com',
          phone: '0123456789',
          level: '3',
          certificate: 'https://i.pravatar.cc/300',
          province: '5',
          password: await bcrypt.hash('password', 10),
          birthday: '1999-01-01',
          nationality: 'VN',
        },
        {
          name: 'Trịnh Huy Bằng',
          gender: '1',
          avatar: 'https://i.pravatar.cc/300',
          email: 'user5@gmail.com',
          phone: '0123456789',
          level: '3',
          certificate: 'https://i.pravatar.cc/300',
          province: '5',
          password: await bcrypt.hash('password', 10),
          birthday: '1999-01-01',
          nationality: 'VN',
        },
        {
          name: 'Ngô Bảo Đại',
          gender: '1',
          avatar: 'https://i.pravatar.cc/300',
          email: 'user6@gmail.com',
          phone: '0123456789',
          level: '3',
          certificate: 'https://i.pravatar.cc/300',
          province: '5',
          password: await bcrypt.hash('password', 10),
          birthday: '1999-01-01',
          nationality: 'VN',
        },
        {
          name: 'Võ Tá Hoan',
          gender: '1',
          avatar: 'https://i.pravatar.cc/300',
          email: 'user7@gmail.com',
          phone: '0123456789',
          level: '3',
          certificate: 'https://i.pravatar.cc/300',
          province: '5',
          password: await bcrypt.hash('password', 10),
          birthday: '1999-01-01',
          nationality: 'VN',
        },
        {
          name: 'Nguyễn Thị Hoài Thu',
          gender: '1',
          avatar: 'https://i.pravatar.cc/300',
          email: 'user8@gmail.com',
          phone: '0123456789',
          level: '5',
          certificate: 'https://i.pravatar.cc/300',
          province: '4',
          password: await bcrypt.hash('password', 10),
          birthday: '1999-01-01',
          nationality: 'VN',
        },
        {
          name: 'Nguyễn Hà Linh',
          gender: '1',
          avatar: 'https://i.pravatar.cc/300',
          email: 'user9@gmail.com',
          phone: '0123456789',
          level: '5',
          certificate: 'https://i.pravatar.cc/300',
          province: '4',
          password: await bcrypt.hash('password', 10),
          birthday: '1999-01-01',
          nationality: 'VN',
        },
        {
          name: 'Nguyễn Việt Hoàng',
          gender: '1',
          avatar: 'https://i.pravatar.cc/300',
          email: 'user10@gmail.com',
          phone: '0123456789',
          level: '3',
          certificate: 'https://i.pravatar.cc/300',
          province: '4',
          password: await bcrypt.hash('password', 10),
          birthday: '1999-01-01',
          nationality: 'VN',
        },
        {
          name: 'うちはサスケ',
          gender: '1',
          avatar: 'https://i.pravatar.cc/300',
          email: 'user11@gmail.com',
          phone: '0123456789',
          level: '1',
          certificate: 'https://i.pravatar.cc/300',
          province: '4',
          password: await bcrypt.hash('password', 10),
          birthday: '1999-01-01',
          nationality: 'JP',
        },
        {
          name: 'うずまきナルト',
          gender: '1',
          avatar: 'https://i.pravatar.cc/300',
          email: 'user12@gmail.com',
          phone: '0123456789',
          level: '1',
          certificate: 'https://i.pravatar.cc/300',
          province: '4',
          password: await bcrypt.hash('password', 10),
          birthday: '1999-01-01',
          nationality: 'JP',
        },
      ])
      .execute();
  }
}
